import os

DISCORD_API_KEY = os.environ.get("DISCORD_API_KEY")
DISCORD_SERVER_KEY = os.environ.get("DISCORD_SERVER_KEY")
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
SPEAK_CHAT_DEFAULT_CHANNEL_ID = os.environ.get("SPEAK_CHAT_DEFAULT_CHANNEL_ID")
