version: '3'
services:
  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - .:/root/src
    environment:
      DISCORD_API_KEY: ${DISCORD_API_KEY}
      DISCORD_SERVER_KEY: ${DISCORD_SERVER_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SPEAK_CHAT_DEFAULT_CHANNEL_ID: ${SPEAK_CHAT_DEFAULT_CHANNEL_ID}
    command:
      python app.py
    tty: yes
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - 50021:50021
    tty: yes
